services:
  db:
    image: focker.ir/postgres:15.13-bullseye
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
#    image: ghcr.io/amir-ys/nobat:latest
    ports:
      - "8001:80"
    restart: unless-stopped
    working_dir: /app
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
#    volumes:
#        - ./:/app


volumes:
  pgdata:
