version: "3.8"

services:
  db:
    image: focker.ir/postgres:15.13-bullseye
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: fastapi-app
    ports:
      - "8001:80"
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}

volumes:
  pgdata:
